spring:
  application:
    name: praktikum_final_project

kafka:
  bootstrap-servers: localhost:9093, localhost:9095, localhost:9097
  acks: all
  retries: 3
  replicas: 2
  topic-products: products
  topic-deprecated-products: deprecated-products
  topic-filtered-products: filtered-products
  topic-clients-request: clients-request
server:
  port: 8888
